version: "3"
services:
  translation-tool-app-dev:
    command: npm run dev
    build: .
    depends_on:
      - translation-tool-db-dev
    env_file:
      - ./.env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src
    networks:
      - db-network
  translation-tool-db-dev:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.env
    ports:
      - "${TYPEORM_PORT}:${TYPEORM_PORT}"
    environment:
      MYSQL_USER: "${TYPEORM_USERNAME}"
      MYSQL_PASSWORD: "${TYPEORM_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${TYPEORM_PASSWORD}"
      MYSQL_DATABASE: "${TYPEORM_DATABASE}"
    networks:
      - db-network
networks:
  db-network:
    driver: bridge
