version: "3"
services:
  translation-tool-app:
    command: npm run dev
    build: .
    depends_on:
      - translation-tool-db
    env_file:
      - ./.env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - our_net
    expose:
      - "${PORT}"

  translation-tool-db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "bluebird2011"
      POSTGRES_DB: "LocalizationServer"
      PGDATA: "/app/data/postgres"
    networks:
      - our_net
    volumes:
      - test_volume:/app/data/postgres
    expose:
      - "5432"

volumes:
  test_volume:

networks:
  our_net:
    driver: bridge
