version: "3"
services:
  translation-client:
    command: yarn start
    build: ./newClient
    ports:
      - "8443:8443"
    networks:
      - our_net
    expose:
      - "8443"
  translation-tool-app:
    command: npm run dev
    build: .
    depends_on:
      - translation-tool-db
    env_file:
      - ./.env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - our_net
    expose:
      - "${PORT}"

  translation-tool-db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - /app/src/db/seed/postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "bluebird2011"
      POSTGRES_DB: "LocalizationServer"
      PGDATA: "/app/src/db/seed/postgres"
    networks:
      - our_net
    expose:
      - "5432"

networks:
  our_net:
    driver: bridge
